# Add project specific ProGuard rules here.
# You can control the set of applied configuration files using the
# proguardFiles setting in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# If your project uses WebView with JS, uncomment the following
# and specify the fully qualified class name to the JavaScript interface
# class:
#-keepclassmembers class fqcn.of.javascript.interface.for.webview {
#   public *;
#}

# Keep readable stack traces in Play Console crash reports.
-keepattributes SourceFile,LineNumberTable
-renamesourcefileattribute SourceFile

# --- DugoutIQ keep rules ---------------------------------------------------
# Capacitor plugins, the WebView JS bridge, and the Cordova purchase plugin
# are already protected by @capacitor/android's bundled consumerProguardFiles.
# Firebase and RevenueCat ship their own consumer rules via their AARs.
# The rules below are defensive extras for the revenue-critical paths, since
# a mis-shrunk purchase flow would fail silently.

# Cordova purchase plugin (cc.fovea.*) — reflection-loaded by Cordova.
-keep class cc.fovea.** { *; }

# RevenueCat public API + models (billing).
-keep class com.revenuecat.purchases.** { *; }

# Capacitor bridge core (belt-and-suspenders alongside the consumer rules).
-keep class com.getcapacitor.** { *; }
-keep class com.capacitorjs.** { *; }

# The Firebase Authentication plugin has an OPTIONAL Facebook-login provider
# that references the Facebook SDK. We don't use Facebook sign-in, so that SDK
# isn't bundled — tell R8 those references are safe to ignore (it can't
# reach that code path). Rules generated by R8's missing_rules.txt.
-dontwarn com.facebook.**
